// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjGq-mYT0LfFuqT89UNaMUDpovgHLtMVo',
    appId: '1:454485172944:web:a8c99af33304e74e6274d5',
    messagingSenderId: '454485172944',
    projectId: 'martialflow-9424d',
    authDomain: 'martialflow-9424d.firebaseapp.com',
    storageBucket: 'martialflow-9424d.firebasestorage.app',
    measurementId: 'G-4SG5YB3C3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-jXCj6XBRq5grj7Utc5lYkF919c0jfes',
    appId: '1:454485172944:android:073a7b2935cc53636274d5',
    messagingSenderId: '454485172944',
    projectId: 'martialflow-9424d',
    storageBucket: 'martialflow-9424d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfszHRQCyLhnI1j8A9mvU_Xe4twM-Gpjk',
    appId: '1:454485172944:ios:a7ae524a85f2ed156274d5',
    messagingSenderId: '454485172944',
    projectId: 'martialflow-9424d',
    storageBucket: 'martialflow-9424d.firebasestorage.app',
    iosBundleId: 'com.example.martialflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfszHRQCyLhnI1j8A9mvU_Xe4twM-Gpjk',
    appId: '1:454485172944:ios:a7ae524a85f2ed156274d5',
    messagingSenderId: '454485172944',
    projectId: 'martialflow-9424d',
    storageBucket: 'martialflow-9424d.firebasestorage.app',
    iosBundleId: 'com.example.martialflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjGq-mYT0LfFuqT89UNaMUDpovgHLtMVo',
    appId: '1:454485172944:web:fd67bf391228491f6274d5',
    messagingSenderId: '454485172944',
    projectId: 'martialflow-9424d',
    authDomain: 'martialflow-9424d.firebaseapp.com',
    storageBucket: 'martialflow-9424d.firebasestorage.app',
    measurementId: 'G-PZM00V9YYK',
  );
}
